### ISSUE TITLE
🐛 BUG: Viewing replies on a profile results in a `Client-side Exception Occurred`

### ISSUE THREAD

**Issue by dusthijsvdh** [dailydotdev/daily#1108]
### What went wrong? 🤔

I opened my replies tab on my profile and I got a `Client-side Exception Occurred` message

### Expected Behavior

See my replies

### Steps to Reproduce Issue

```bash
1. Go to `https://app.daily.dev/<USERNAME>/replies`
```
e.g. https://app.daily.dev/tvdheijden/replies

### Solution Proposed

According to the console, something related to usernames.

### Screenshots

![image](https://github.com/dailydotdev/daily/assets/25427808/2dc21cda-21a8-4f43-b55d-2d83faaab3a3)

### Environment

Windows 11, Microsoft Edge for Business 123.0.2420.65 (Official build) (64-bit)

### Browsers

Microsoft Edge

### OS

Windows

### Version of daily.dev

3.31.3

### Additional Context

```bash
framework-675cd073cc0eab1c.js:1  TypeError: Cannot read properties of undefined (reading 'username')
    at k (9513-91ebb85d8eda8c7b.js?__WB_REVISION__=91ebb85d8eda8c7b:1:1673)
    at oo (framework-675cd073cc0eab1c.js:1:59416)
    at Ku (framework-675cd073cc0eab1c.js:1:111716)
    at Li (framework-675cd073cc0eab1c.js:1:98957)
    at Ni (framework-675cd073cc0eab1c.js:1:98885)
    at Pi (framework-675cd073cc0eab1c.js:1:98748)
    at bi (framework-675cd073cc0eab1c.js:1:95714)
    at framework-675cd073cc0eab1c.js:1:45208
    at t.unstable_runWithPriority (framework-675cd073cc0eab1c.js:1:129353)
    at Ql (framework-675cd073cc0eab1c.js:1:44985)
cu @ framework-675cd073cc0eab1c.js:1
main-0a5a46643a77ae81.js:1  TypeError: Cannot read properties of undefined (reading 'username')
    at k (9513-91ebb85d8eda8c7b.js?__WB_REVISION__=91ebb85d8eda8c7b:1:1673)
    at oo (framework-675cd073cc0eab1c.js:1:59416)
    at Ku (framework-675cd073cc0eab1c.js:1:111716)
    at Li (framework-675cd073cc0eab1c.js:1:98957)
    at Ni (framework-675cd073cc0eab1c.js:1:98885)
    at Pi (framework-675cd073cc0eab1c.js:1:98748)
    at bi (framework-675cd073cc0eab1c.js:1:95714)
    at framework-675cd073cc0eab1c.js:1:45208
    at t.unstable_runWithPriority (framework-675cd073cc0eab1c.js:1:129353)
    at Ql (framework-675cd073cc0eab1c.js:1:44985)
ee @ main-0a5a46643a77ae81.js:1
main-0a5a46643a77ae81.js:1  A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ee @ main-0a5a46643a77ae81.js:1
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Thanks for logging, we'll look at this right away 🙏

**Comment by rebelchris** [comment]
@dusthijsvdh thanks a lot for reporting this issue.
We managed to solve it, and you should be able to view the page again 🙏
