### ISSUE TITLE
Page Crashed🐛 BUG: 

### ISSUE THREAD

**Issue by sirEmmyUche** [dailydotdev/daily#926]
### What went wrong? 🤔

The homepage keeps crashing when trying to deploy or run from localhost for inspection. 
There's an error with hooks been improperly used or an old version of react. 

### Expected Behavior

Expected to show homepage or viewpage

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Environment

windows 10

### Additional Context

```bash
Uncaught runtime errors:
×
ERROR
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (webpack-internal:///./node_modules/react/cjs/react.development.js?1b7e1:1476:13)
    at useEffect (webpack-internal:///./node_modules/react/cjs/react.development.js?1b7e1:1519:20)
    at useKeyboardNavigation (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/hooks/useKeyboardNavigation.js:22:85)
    at Layout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/index.js:25:115)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:14985:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:17811:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:19049:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:3994:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:4056:31)
ERROR
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (webpack-internal:///./node_modules/react/cjs/react.development.js?1b7e1:1476:13)
    at useEffect (webpack-internal:///./node_modules/react/cjs/react.development.js?1b7e1:1519:20)
    at useKeyboardNavigation (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/hooks/useKeyboardNavigation.js:22:85)
    at Layout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/index.js:25:115)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:14985:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:17811:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:19049:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:3994:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js?ac890:4056:31)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment]
Hi @sirEmmyUche this is referring to the docs project I assume?
Can I transfer the ticket to that repo so the right people can help you resolve it?
